### PR TITLE
Update ReverseArray.java

### PR DESCRIPTION
**Pull request by binario200**
This is an useless change but I'm using this to invite you @lordzero0000 @Xotl @bandaca @juveguevara @bandax to help me to understand how this algorithm works, suggest improvements, jokes or something like that. 

P.S: sorry if I hurt your intelligence using java, I'm just following some books examples, we could move this to other languages is you wish guys.

### CODE REVIEW

**Comment by Xotl** [comment]
Are you trying to implement a reverse array algorithm and you want some implementation examples?.

**Comment by Xotl** [comment]
Also, if you want to practice i highly recommend [HackerRank](https://www.hackerrank.com/), you can start with the [Warm Up section](https://www.hackerrank.com/domains/algorithms/warmup).

**Comment by binario200** [comment]
@Xotl I'm following a book examples. I just asking help to understand this one (and other algorithms that I will upload code here) 

Understand for example:
- why the algorithm uses N/2 at the for loop
- improvements or even the big O notation. 
- things like that, as an study group. 

also I will check hacker rank.

**Comment by Xotl** [comment]
Well, it seems that the array has a `O(N/2)` complexity. This is because the number in the middle (if array lenght it's odd) does not need to be moved and it interchanges the numbers until the index is the middle number position. 

Imagine that the array is sliced in two parts, left and right. Then you start interchanging the numbers between these two groups and you start interchanging the first number on the left side and the last number on the right side, and you keep interchangin numbers until you "meet" in the middle.

**Comment by binario200** [comment]
@Xotl that's it, is similar What I thought in [my explanation](https://github.com/binario200/algorithms101/blob/master/ReverseArray.java#L12) 

Now, why is 0(N/2) I'm not sure about the understand the idea behind N/2

**Pull request merged**
